<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVeCMYR5\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVeCMYR5/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVeCMYR5.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVeCMYR5\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerVeCMYR5\App_KernelDevDebugContainer([
    'container.build_hash' => 'VeCMYR5',
    'container.build_id' => 'bb4b34bd',
    'container.build_time' => 1705401438,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVeCMYR5');
